# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A_qQzenA7PyNaYCGHCl5gHZDDydTQDip
"""

import re
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
plt.style.use('dark_background')

file_path = '/content/drive/MyDrive/Python/test 220103/export_sample.xml'
# file_path = '/content/drive/MyDrive/Python/test 220103/export_cda.xml'

df = pd.DataFrame([], columns=['date', 'bpm'])
pattern = '^.*IdentifierHeartRate".*startDate="(.{19}).*value="([0-9]*).*$'

with open(file_path, 'r') as f:
    for line in f:
        search = re.search(pattern, line)
        if search is not None:
            
            df = df.append({'date': search.group(1),'bpm': search.group(2)}, ignore_index=True)

df.date = pd.to_datetime(df.date)
df.bpm = pd.to_numeric(df.bpm)

df = df.set_index('date')
df = df.sort_index()

df.head()

plt.figure(figsize=(20, 8))
sns.lineplot(x=df.index, y=df.bpm)
plt.show()

plt.figure(figsize=(12, 8))
sns.kdeplot(x=df.bpm, fill=True)
plt.show()

df_211103 = df.loc['2021-11-03']

df_211103

plt.figure(figsize=(20, 8)) 
sns.lineplot(x=df_211103.index, y=df_211103.bpm)
plt.show()

notes = [{
        'time': '2021-11-03 12:45:00',
        'note': 'Kiss'
    }, {
        'time': '2021-11-03 17:00:00',
        'note': 'Coding'
    }, {
        'time': '2021-11-03 18:10:00',
        'note': 'Dinner'
}]

dt = pd.to_datetime('2021-11-03 12:45:00')

df_211103.index.get_loc(dt, method='nearest')

plt.figure(figsize=(20, 8)) 
sns.lineplot(x=df_211103.index, y=df_211103.bpm)

for note in notes:
    dt = pd.to_datetime(note['time'])
    idx = df_211103.index.get_loc(dt, method='nearest')

    plt.annotate(
        note['note'],
        (df_211103.iloc[idx].name, df_211103.iloc[idx].bpm),
        xytext=(10, 50), 
        textcoords='offset points',
        arrowprops=dict(arrowstyle='-|>'),
        fontsize=30
    )

plt.show()